name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
    
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Test with pytest
      run: |
        pytest
    
    - name: Check file structure
      run: |
        echo "Checking if essential files exist..."
        test -f "app/server_windows_improved.py" || exit 1
        test -f "app/index_corrigido.html" || exit 1
        test -f "app/script_corrigido.js" || exit 1
        test -f "app/styles.css" || exit 1
        test -f "iniciar_windows_melhorado.bat" || exit 1
        test -f "README.md" || exit 1
        echo "✅ All essential files present" 